### ISSUE TITLE
Parser syntax errors should be passed to the callback, not thrown

### ISSUE THREAD

**Issue by brettstimmerman** [linkedin/dustjs#107]
Originally submitted as akdubya/dustjs#12:

> When the parser encounters a syntax error, it currently throws a SyntaxError exception instead of bubbling it up to the render callback like I'd expect. Catching this exception is proving to be a challenge in an Express app. I'd much rather be able to handle it in my callback.
> 
> This will throw a SyntaxError in Node (run it as a file, though; the REPL catches and hides the exception):
> 
> ``` js
> var dust    = require('dust'),
>     context = dust.makeBase();
> 
> dust.renderSource('{<body}no end tag', context, function (err, html) {
>     if (err) {
>         console.log('I got an error!'); // never gets here
>     }
> });
> ```

**Comment by sielay** [comment]
I think it's still relevant in 2.7.4

If you take a look on the lines: https://github.com/linkedin/dustjs/blob/2.7/lib/dust.js#L171 and https://github.com/linkedin/dustjs/blob/2.7/lib/compiler.js#L34

If you implement your own `onLoad` and it will return content as a string (won't perform `dust.compile` on it's own) then you'll get error like

```
Uncaught SyntaxError: Expected end tag for ... but it was not found. At line : 2, column : 1
      at Object.compiler.compile (node_modules/dustjs-linkedin/lib/compiler.js:34:13)
      at done (node_modules/dustjs-linkedin/lib/dust.js:171:49)
```

I tried on such example of `onLoad`

```javascript
(templateName, options, callback) => {

        debug('onLoad ' + templateName);

        if (dust.cache[templateName]) {
            return dust.cache[templateName];
        }

        pathResolver(templateName)
            .then(filePath => fs
                .readFile(filePath, 'utf8', (error, content) => {
                    if (error) {
                        debug('error ' + error);
                        return callback(error);
                    }
                    console.log('content', content);
                    callback(null, content);
                }))
            .catch(error => callback(error));
    };
```
