### ISSUE TITLE
Can't use context variable to load partials

### ISSUE THREAD

**Issue by jandrieu** [linkedin/dustjs#713]
I'm trying to use an array of partial names to drive a series of includes so as to inject a bunch of javascript files as inline script elements.

I have the context ```{scripts:['first','second']}```
Those are also the names of partials that are loaded.

I can get a section working that creates the remote script elements, i.e., with a src attrbitue:
```
<!DOCTYPE html>
<html>
  <body>
    {#scripts}
    <script src="{.}"></script>
    {/scripts}
  </body>
</html>
```

But I'd like to place those scripts inline with something like this:
```
<!DOCTYPE html>
<html>
  <body>
    {#scripts}
    <script>
      {>{.}\}
    </script>
    {/scripts}
  </body>
</html>
```
Unfortunately, that gives me the following error:
```
/home/joe/Software/flattnd/node_modules/dustjs-linkedin/lib/compiler.js:34
      throw new SyntaxError(err.message + ' At line : ' + err.line + ', column : ' + err.column);
      ^

SyntaxError: Expected end tag for scripts but it was not found. At line : 6, column : 7
    at Object.compiler.compile (/home/joe/Software/flattnd/node_modules/dustjs-linkedin/lib/compiler.js:34:13)
    at render (/home/joe/Software/flattnd/arrayfail/arrayPartials.js:67:23)
    at flattn (/home/joe/Software/flattnd/arrayfail/arrayPartials.js:79:3)
    at Object.<anonymous> (/home/joe/Software/flattnd/arrayfail/arrayPartials.js:83:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
```

FWIW, I am using precompiled partials. Those compile and load fine. In fact, if I don't use the array section {#scripts}, I can load them just fine.  

```
<!DOCTYPE html>
<html>
  <body>
    {#scripts}
    <script>
      {.}
    </script>
    {/scripts}
    <script>
    {>first/}
    </script>
    <script>
    {>second/}
    </script>
  </body>
</html>
```

That results in 
```
 <!DOCTYPE html>
<html>
  <body>
  <script>first</script>
  <script>second</script>
  <script>
    $(document).ready(function(){alert('first!');});
  </script>
  <script>
    $(document).ready(function(){alert('second...');});
  </script>
</body>
</html>
```

So the compilation and loading look find. It's rendering that array of partials that seems to be problematic.  

Is there a way to do that?

**Comment by sethkinast** [comment]
To use a variable in a partial invocation, use quotes:

{>"{.}"/}

**Comment by jandrieu** [comment]
Thank you!  I thought I tried that, but it must have been something else I was doing wrong. Much appreciated.
