### ISSUE TITLE
very Poor support for debugging .. where should find this @gt /gt i have 1000 lines of code ??

### ISSUE THREAD

**Issue by tkssharma** [linkedin/dustjs#746]
Unhandled rejection SyntaxError: Expected end tag for gt but it was not found. At line : 39, column : 94
    at Object.compiler.compile (/var/www/liveHT/node_modules/dustjs-linkedin/lib/compiler.js:34:13)
    at done (/var/www/liveHT/node_modules/dustjs-linkedin/lib/dust.js:171:49)
    at /var/www/liveHT/node_modules/xdust/lib/duster.js:42:24
    at /var/www/liveHT/reader/databaseReader.js:8:29
    at tryCatcher (/var/www/liveHT/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/liveHT/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/var/www/liveHT/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/var/www/liveHT/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/www/liveHT/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/var/www/liveHT/node_modules/bluebird/js/release/promise.js:636:18)
    at /var/www/liveHT/node_modules/bluebird/js/release/nodeback.js:42:21
    at Query.<anonymous> (/var/www/liveHT/node_modules/mongoose/lib/model.js:3336:16)
    at /var/www/liveHT/node_modules/kareem/index.js:259:21

**Comment by sethkinast** [comment]
On line 39 of whatever template you are processing at that time.
