### ISSUE TITLE
The examples on dustjs.com do not work

### ISSUE THREAD

**Issue by brianmhunt** [linkedin/dustjs#780]
In the developer console:

```
Uncaught DOMException: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at HTMLElement.shadowFromTemplate (http://www.dustjs.com/bower_components/polymer/polymer.js:10033:25)
    at HTMLElement.parseDeclaration (http://www.dustjs.com/bower_components/polymer/polymer.js:10005:25)
    at HTMLElement.parseDeclarations (http://www.dustjs.com/bower_components/polymer/polymer.js:9986:28)
    at HTMLElement.makeElementReady (http://www.dustjs.com/bower_components/polymer/polymer.js:9886:12)
    at HTMLElement.createdCallback (http://www.dustjs.com/bower_components/polymer/polymer.js:9855:14)
    at HTMLElement.registerPrototype (http://www.dustjs.com/bower_components/polymer/polymer.js:11299:28)
    at HTMLElement.register (http://www.dustjs.com/bower_components/polymer/polymer.js:11127:12)
    at HTMLElement._register (http://www.dustjs.com/bower_components/polymer/polymer.js:11635:12)
    at Object.flush (http://www.dustjs.com/bower_components/polymer/polymer.js:11471:28)
    at Object.ready (http://www.dustjs.com/bower_components/polymer/polymer.js:11486:12)
```

**Comment by jbaicoianu** [comment]
I also see this problem in Chrome.  It works in Firefox.

**Comment by LoveraSantiago** [comment]
On Internet Explorer Its possible to see text on black textArea, on chrome Its not possible see anything. 
Lost several minutes trying typing things to see how it works and bahn!!!!

**Comment by nricardo** [comment]
Also confirmed to work in Firefox. Chrome 👎

**Comment by CExCDavies** [comment]
In Chrome 45, the ability to have multiple shadow roots was deprecated. (seehttps://developer.mozilla.org/en-US/docs/Web/API/Element/createShadowRoot#Browser_compatibility)

**Comment by ggiak** [comment]
+1 for this issue on chrome.

**Comment by treyhuffine** [comment]
+2 for this issue on chrome.

**Comment by jbaicoianu** [comment]
I spoke with someone who works at LinkedIn, unfortunately he said that internally they consider dustjs to be deprecated, and likely don't have anyone assigned to it.  Shame, I've been using dustjs for 8 years and it's worked great since then, still does, but seems like another victim of the framework popularity contest :(

**Comment by brianmhunt** [comment]
@jbaicoianu Thanks for sharing that; this information will undoubted help others who happen across this.

**Comment by gilsondelrei** [comment]
Thanks by important information, maybe  i will consider markojs how my
Future template mechanism.

Em seg, 16 de abr de 2018 12:32, Brian M Hunt <notifications@github.com>
escreveu:

**Comment by danwdart** [comment]
For those still on this - whilst it still needs a maintainer, it also still needs this issue and possibly others fixing.

**Comment by Ampakinetic** [comment]
It still says "Dust.js by LinkedIn" on the site so it's not a good reflection on them if none of the examples show up and they're too lazy to remove some lines of CSS.   I still use DustJS daily and it's an awesome project.  I'd help maintain it if the community somehow got access to the site.

**Comment by kenjim83** [comment]
👍 Still seeing this on Chrome.

**Comment by daniel0128** [comment]
+1 on chrome

**Comment by riteshpanchal** [comment]
Still seeing the issue on Chrome.
